### ISSUE TITLE
hi，i want to try it

### ISSUE THREAD

**Issue by 1096015776** [JoosepAlviste/dotfiles#1]
i get these

when i run packersync

it tell me some function snip error that i cann‘t try it

could you help me，please

i‘m sorry that my english is not ok

**Comment by 1096015776** [comment]
i solve it beacause i no plug but autocmd use vsnip ，i comment this

**Comment by JoosepAlviste** [comment]
Hey @1096015776, glad you got it working!

I'll close this issue for now, feel free to ask questions here though.
