### ISSUE TITLE
Hey，the config is simply but strong, I try it and like it,but I have some questions,if you have time,could you help me

### ISSUE THREAD

**Issue by 1096015776** [JoosepAlviste/dotfiles#2]

**Comment by 1096015776** [comment]
I try neovim config,it is amzing, I found it is simply,but can work well with me,but I'm wrong in something,first,the format is not work, I do not know why,I'm sure that I install all markdown's lsp,then the eslint file in my ~/dotfiles,but when I formating,the error show 

"/nvim/runtime/lua/vim/lsp/handlers.lua:467: bad 
argument #2 to 'format' (number expected, got nil)"

second,I guess you use tabe manage mulit file,but I not find some mapping to jump tabe,
I don't know some tabe skill,if have some skill,could you tell me,thanks.

**Comment by 1096015776** [comment]
![image](https://user-images.githubusercontent.com/40203327/133039001-6e39d72f-4abf-4151-af7e-53291c8ad93d.png)
here is my nvim version
NVIM v0.6.0-dev+1731-gcd4ec810e
Build type: Release
LuaJIT 2.1.0-beta3
编译者 fx@fangxideMacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/HEAD-cd4ec81_2/share/nvim"

Run :checkhealth for more info

**Comment by 1096015776** [comment]
I don not know why but i can use vim.lsp.buf.formatting_sync() to format,
then lua vim.lsp.buf.formatting() give me a error,but now i can format.
emm....I need map formatting_sync()

**Comment by 1096015776** [comment]
Now,is just lsp go decration is not work,it tell me bad argument #2 to 'format' (num
ber expected, got nil)

**Comment by JoosepAlviste** [comment]
Hey! I haven't seen that error before, what filetype are you trying to format? Your screenshot looks like HTML, but I haven't configured any formatters for HTML, how did you configure that? I have overwritten the `textDocument/formatting` handler here: https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/lsp/init.lua#L27, maybe that helps you find out whats going on?

About your second question related to tabs: I don't really use tabs that much and don't have any special mappings for creating or navigating between tabs. I just use `:tabe` to create a new tab (or hit `<C-t>` in Telescope) and `gt` / `gT` to navigate between tabs. I sometimes open the back-end and front-end for my projects in different tabs, but that's about it usually. I mostly just navigate my projects with Telescope `find_files`.

About the declaration error, I've also overwritten the LSP handler for that: https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/lsp/init.lua#L198, maybe removing that helps? Looking back at the LSP overrides, I should probably clean those up a bit 😄

**Comment by 1096015776** [comment]
thanks for your answer,I use file is vue,the vue can format use formatting_sync()
then go definition is ok,can work,just go to declartion is not ok.
![截屏2021-09-13 下午10 16 30](https://user-images.githubusercontent.com/40203327/133100042-c29024c2-d8c3-4093-97c0-2f4678525c89.png)
![截屏2021-09-13 下午10 16 35](https://user-images.githubusercontent.com/40203327/133100098-5a7b0f9f-82da-4aa2-ac32-952f12279874.png)

I read the lsp log

"method textDocument/declaration is not supported by any of the servers registered for the current buffer"

I not found some lsp like match declaration,
but defintion is can work with me,
so it is not important for me.
really thanks for you.
I can feel the work method is perfect.
I belive less is more, I love unix,the config let me feel it.

**Comment by JoosepAlviste** [comment]
Oh I see, I think that you're correct that the Vue LSP does not support declaration, only definition. I always just use definition so I don't notice the lack of declaration, I don't even know what their difference would be 😄 

It's interesting that the formatting doesn't work though, I guess it requires more debugging.

I also feel like it's nice to have this minimal-ish config, I don't really feel the need for fancier things at the moment. Anyways, glad that you're enjoying the config!

If you don't mind, I would close this issue, it looks like you got the set-up pretty much working. Let me know if you have any other questions/thoughts!
