### ISSUE TITLE
Hey , I'm sad about match tag

### ISSUE THREAD

**Issue by 1096015776** [JoosepAlviste/dotfiles#3]
sometime,I need match some tag,Maybe I'm write bad code,I write many tags,on the match let me feel sad,
so I use this plugin to match up tag https://github.com/andymass/vim-matchup
earliy , it is can work with me,it not can work when  I use the nvim config,I don't know why,because I notice that the the match method use html file method , then i try html , it even can match tag.So i'm sad it not work in vue.
if you have some time, could you help me ? I just want to get better match.

**Comment by 1096015776** [comment]
I remove the vue scm file it can work,I don't know what scm is what to do, but now i feel nice.

**Comment by JoosepAlviste** [comment]
Hey! Did you follow the [treesitter integration instructions](https://github.com/andymass/vim-matchup#tree-sitter-integration)? I installed the plugin and followed the instructions and it seems to work OK for me:

<img width="707" alt="image" src="https://user-images.githubusercontent.com/9450943/133799730-282387f0-37b3-4878-9b95-7d174c1b9e43.png">

**Comment by 1096015776** [comment]
I don't know what happen,when i remove vu scm file then it work,so i think maybe scm file let it not work, as you said,I plan to read the documention,i add the i remove vue scm file,but the match up can work.thanks for your work,i'm sorry that it is easy to try, i should be careful to read the documentation.
thanks for your work.
