### ISSUE TITLE
hey,i have some troubles ,cloud you help me? 

### ISSUE THREAD

**Issue by 1096015776** [JoosepAlviste/dotfiles#5]
I note there is something change,I try it ,it become better,but at format i have some question,early,it use defalut eslint to format if project have no lint file,now it change,my project have no eslint file,I'm sorry that I don't know write style lint json for me,cloud you give me your .stylelintrc.json  and .prettierrc.json,thanks

**Comment by JoosepAlviste** [comment]
Hey!

I recently changed to use the ESLint language server but I'm not sure how exactly it works when there is no config file. You could try commenting out the eslint language server setup here: https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/lsp/eslint_ls.lua and commenting in the null_ls eslint_d config here: https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/lsp/null_ls.lua

I don't have any default eslint config though, I think that all of my projects have their own eslint config.

About stylelint, it should only be enabled if your project has a `.stylelintrc.json` file. Does it show some error for you?

For `.prettierrc.json`, I think that a simple file like this should work and configure Prettier with default settings:

```json
{}
```

Maybe the same empty config file would work for eslint and stylelint?

**Comment by 1096015776** [comment]
thanks for your answer,I try it ,I change the null-ls let peritter to format and eslint to diagnotic ,i found i can use, thanks , your file always is less but strong.
