### ISSUE TITLE
List of applications

### ISSUE THREAD

**Issue by HorrorPills** [JoosepAlviste/dotfiles#6]
Can you please list all the applications you use for this rice? I feel that not all of them are listed on the main page of this project.

**Comment by JoosepAlviste** [comment]
Hey! Which exact applications do you mean? I think that the important ones are listed in the README, but I'll write down the ones that can be seen in the screenshots:

- Terminal: Kitty
- Shell: Zsh
- Window manager: Yabai (though I have stopped using it)
- Editor: Neovim
- System info display: Neofetch
- `ls` replacement: Exa

I have some other configurations here: https://github.com/JoosepAlviste/dotfiles/tree/master/config but I don't think that they're really a part of the "rice" so to say 😄 

Anyways, was there anything else you were interested in?

**Comment by JoosepAlviste** [comment]
Closing as inactive, let me know if there are more questions
