### ISSUE TITLE
Featuring your dotfiles on my newsletter!

### ISSUE THREAD

**Issue by adibhanna** [JoosepAlviste/dotfiles#7]
Hi there!

Love your dotfiles configs. I would love to feature it in my dotfiles newsletter https://dotfiles.substack.com/

If you're down, please check https://dotfiles.substack.com/about for details on some info!

cheers

**Comment by JoosepAlviste** [comment]
Hey, sounds fun! I sent you an email with the answers to the questions. Let me know if there's anything I should elaborate on more.

Thanks for reaching out!
