### ISSUE TITLE
Makesymlink don't work, missing makesymlink.sh

### ISSUE THREAD

**Issue by gummipunkt** [JoosepAlviste/dotfiles#8]
Makesymlink don't work. Installed as written in README

---

`~/Documents/dotfiles on master`
`% chmod +x bin/makesymlinks.sh`
`chmod: bin/makesymlinks.sh: No such file or directory`

---

`~/Documents/dotfiles/bin on master`
`% ls`
`did          extract      fzf-preview  kp           makesymlinks project`

---

`~/Documents/dotfiles/bin on master`
`% chmod +x makesymlinks`

---

`~/Documents/dotfiles/bin on master`
`% ./makesymlinks                   `
`Creating /Users/patrickwalter/.dotfiles_old for backup of any existing dotfiles in ~`
`...done`
`Changing to the /Users/patrickwalter/dotfiles directory`
`./makesymlinks: line 25: cd: /Users/patrickwalter/dotfiles: No such file or directory`
`...done`
`./makesymlinks: line 33: [: too many arguments`
`./makesymlinks: line 38: [: too many arguments`
`./makesymlinks: line 47: [: too many arguments`

**Comment by JoosepAlviste** [comment]
Thanks for letting me know! You're right, the symlinking script requires the dotfiles to be cloned to `~/dotfiles` which shouldn't be a hard requirement. I made it so that you could clone it anywhere. Also, I fixed the `makesymlinks` references in the README.
