### ISSUE TITLE
How is the file name displayed?

### ISSUE THREAD

**Issue by itsuki0927** [JoosepAlviste/dotfiles#9]
![image](https://github.com/JoosepAlviste/dotfiles/assets/40518195/e60c11c6-6e53-4488-99d0-fc4b95d67a94)

Hi, I like your nvim config very much, I would like to ask how to realize the filename in this place, I thought it was tabline at first, then I tried to realize it with your config, but I found that it's not right, so I would like to ask where this piece of realization is ah!

**Comment by JoosepAlviste** [comment]
Hey! The screenshots in the README are a bit old and I don't use that plugin anymore. I should really update the screenshots 😅 

But the plugin is https://github.com/b0o/incline.nvim with this configuration: https://github.com/JoosepAlviste/dotfiles/blob/before_simplify/config/nvim/lua/j/plugins/incline.lua

**Comment by itsuki0927** [comment]
Okay, okay. Thanks for the reply.
